### PR TITLE
Updated for 8-18

### PR DESCRIPTION
**Pull request by edjiang**
We need to increment the version of vapor/tls once they publish a new release as well. However, there are some problems right now with COpenSSL on Mac. Otherwise, this works on linux just fine (and on my machine, with COpenSSL hacked to work)

https://github.com/vapor/tls/pull/8

### CODE REVIEW

**Comment by tannernelson** [comment]
Woot. I'm starting to make my way up Vapor's deps as we speak.

**Comment by edjiang** [comment]
I believe this should work after https://github.com/vapor/tls/pull/9 gets merged.

**Comment by edjiang** [comment]
vapor/tls is merged, so this is ready

**Comment by czechboy0** [comment]
👍

**Comment by czechboy0** [comment]
https://github.com/czechboy0/SecretSocks/releases/tag/0.6.0

**Pull request merged**
